openapi: 3.0.0
info:
  version: 1.0.0
  title: Postman Student Community Badge Verifier
  description: >
    This API validates whether a given email or multiple emails are eligible
    for the Student Expert and/or Student Leader roles based on badges. It
    integrates with the Badgr API for badge validation.
servers:
  - url: "https://<your-replit-url>.replit.co"
    description: Production server
paths:
  /:
    get:
      summary: "Root endpoint"
      description: "Returns a simple 'OK' response to indicate the API is running."
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /health:
    get:
      summary: "Health check for the service"
      operationId: healthCheck
      description: "Checks the health status of the API service."
      responses:
        "200":
          description: "Service is healthy"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  timestamp:
                    type: string
                    format: date-time
                required:
                  - status
                  - timestamp
  /validate:
    post:
      summary: "Validate eligibility for a single email"
      operationId: validate
      description: >
        Validates whether a single email is eligible for Student Expert and/or
        Student Leader roles based on their badge information.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
              required:
                - email
      responses:
        "200":
          description: "Eligibility check successful"
          content:
            application/json:
              schema:
                type: object 
                properties:
                  message: 
                    type: string 
                  requestCost:
                    type: string
                  rateLimitRemaining:
                    type: string
                required: 
                  - message
                  - requestCost
                  - rateLimitRemaining
        "403":
          description: "Invalid or missing API key"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /validate-multiple:
    post:
      summary: "Validate eligibility for multiple emails"
      operationId: validateMultiple
      description: >
        Validates whether multiple email addresses are eligible for Student Expert
        and/or Student Leader roles based on their badge information.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emails:
                  type: array
                  items:
                    type: string
              required:
                - emails
      responses:
        "200":
          description: "Eligibility check successful for multiple emails"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    email:
                      type: string
                    message:
                      type: string
                    requestCost:
                      type: string
                    rateLimitRemaining:
                      type: string
                  required:
                    - email
                    - message
                    - requestCost
                    - rateLimitRemaining
        "403":
          description: "Invalid or missing API key"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum: [error]
        message:
          type: string
        errors:
          type: array
          items: {} # any type. This property supplied in case of request validation errors
